### ISSUE TITLE
Conditionals 

### ISSUE THREAD

**Issue by samjtozer** [zhigang1992/react-native-jsonschema-form#1]
Does this library support conditional rendering? I.e. some field A value should render a field B? Thanks for porting this over to Native as well!

**Comment by zhigang1992** [comment]
Theoretically it supports everything react-jsonschema-form supports. It's just a theme for jsonschema form. If it doesn't that means something is missing and we should fix that.

**Comment by samjtozer** [comment]
Thanks I'll have a play
